export const REQUIRED_ENV: string[];
export function checkVersions(input: { tag?: string; appVersion?: string; packageVersion?: string }): string[];
export function checkProject(appJson: unknown): string[];
export const PLATFORM_ENV: { android: string[]; ios: string[] };
export function checkEnv(env: Record<string, string | undefined>, options?: { platform?: string; profile?: string }): string[];
export const LEGAL_ENV: string[];
export const PREVIEW_OPTIONAL_ENV: string[];
export function checkStore(input: { storeConfigText: string; env: Record<string, string | undefined> }): string[];
export function checkIdentifiers(appJson: unknown): string[];
export function checkBackend(env: Record<string, string | undefined>): string[];
export function checkOnMain(input: { sha?: string; onMain: boolean | string; what?: string }): string[];
export function checkReleaseRef(input: { ref?: string; sha?: string; onMain: boolean | string }): string[];
export function checkProductionTrigger(eventName?: string): string[];
